## Imputation

As stated in the analytic plan, data was imputed prior to conducting mixed effects models, with 10 iterations on 20 imputed datasets  The predictor matrix is presented in Supplemental Table \@ref(tab:predmat) ; the percent missing for each variable prior to imputation is presented in Supplemental Table \@ref(tab:pobs-girls) for girls and Supplemental Table \@ref(tab:pobs-boys) for boys, along with the influx (overall number of variable pairs \((Y_j,Y_k)\) with \(Y_j\) missing and \(Y_k\) observed, divided by the total number of observed data cells), and outflux (the number of variable pairs with \(Y_j\) observed and \(Y_k\) missing, divided by the total number of incomplete data cells) for each variable. The influx refers to connection to the observed data (ease of imputation, with one representing the highest level of connection to the observed data) the outflux refers to potential contribution to this variable in imputing other data, both on a 0-1 scale with one representing the highest possible levels of influx/outflux. Overall, there was moderate levels of missingness in the current data.