# Discussion

## Transitions Across Exercise Groups

Altogether, transitions between exercise groups was common in both girls and boys. Stability in the 'no exercise for weight loss' group was highest of all three groups, and stability in the 'exercise for weight loss' and 'maladaptive exercise' groups were moderate (~60-70% stability from year-to-year). As hypothesized (\@ref(aims)) transitions were more common to and from 'exercise for weight loss' and 'maladaptive exercise' as compared to the 'no exercise for weight loss' and 'maladaptive exercise' group.  Moderate rates of transition suggest that, amongst the population-based sample, intervening on psychological motivations for exercise is possible and could impact progression from adaptive to maladaptive exercise engagement.

## Rates of Exercise for Weight Loss and Maladaptive Exercise over Time 

Overall, individuals in the ALSPAC sample reported engaging in exercise for weight loss and maladaptive exercise at relatively high rates across adolescence. Hypothesis 2a was supported in that endorsement of both exercise for weight loss and maladaptive exercise increased over time. With regards to exercise for weight loss, with about half of men and about two thirds of women reported exercise for weight loss at least once per month, and one third of men and almost half of women reporting exercise for weight loss at least once per week at age 24.The relatively high and increasing rates of exercise for weight loss across adolescence are consistent with previous research [@allenEatingDisorderSymptom2013] and is of potential concern as previous research in this cohort suggests that exercise for weight loss at age 14 is associated with increased risk of other eating disorder symtpoms [@schaumbergProspectiveAssociationsDriven2022]. Further, this exercise for weight loss appears to be associated with issues for a substantial portion of individuals, including exercise interfering with work, school, and daily activities, exercising for weight loss despite illness or injury, and/or frequently feelings of guilt after missing an exercise session. Transitioning from 'exercise for weight loss' to 'maladaptive exercise' is relatively common, and occurs at a higher rate than transitioning from 'no exercise for weight loss' to a 'maladaptive exercise' state. 

One possible interpretation of the increase in exercise for weight loss over time is that the increase in exercise for weight loss at age 24, specifically, is an artifact of different response options at this age. While it is possible that the variation in response options at this timepoint influenced rates of endoresment, exercise for weight loss also increased steadily for girls between ages 14-18, suggesting that this interpretation does not fully capture the increase in exercise for weight loss across development. A second interpretation of this increase is that, at younger ages, children are more likely to be actively involved in sports and structured exercise programs and are not motivated by weight management, and that weight loss could transition to be a primary motivator for exercise engagement as organized sport participation wanes in later adolescence. The high rates of endorsement of weight loss as a motivator for exercise appear to eclipse rates of excess weight gain and obesity  during this time period, as the rate of obesity (>95th percentile BMI-Z score) at age 15 years in the ALSPAC cohort is 12.4%, with only 1.4% of the sample showing new incedence of obesity between ages 11-15 years [@hughesIncidenceObesityChildhood2011], suggesting that the growing weight loss motivation for exercise is not exclusive to those for whom weight loss may have been medically prescribed. The high rates of endorsement of a weight loss motivation for exercise amongst adolescents and young adults in this sample suggests that the experience of exercise may be 'linked' with weight management, and increasingly so, across adolescent development in this Western cohort. The pairing of exercise and weight management, while generally considered innocucous or even beneficial, may be problematic on a population scale for the following reasons: 

(1) Weight loss is not indicated for the high percentage of the adolescent population endorsing this motivation.

(2) High doses of exercise may be necessary in order for exercise to be an effective weight loss strategy [@swiftEffectsExercisePhysical2018; @stonerExerciseDoseWeight2019].

(3) A focus on the external motivation of weight loss to support exercise engagement may diminish the potency of non-weight oriented motivations and intrinsic reinforcers associated with exercise over time. As compared to external motivations, autonomous motivators are more likely to support long-term health behavior change [@deciSelfdeterminationTheoryMacrotheory2008; @ngSelfDeterminationTheoryApplied2012].

(4) Exercise for weight loss may lead to maladaptive exercise, a pattern observed over time in the current sample, and can exacerbate eating disorder risk amongst high-risk youth.  

## Predictors of Maladaptive Exercise

### Eating Disorder Cognitions

With regards to predictors of maladaptive exercise, as expected in Hypothesis 2c, eating disorder cognitions at age 14 predicted increased odds for exercise for weight loss and maladaptive exercise across adolescent and young adult development. The most consistent and strongest cognitive predictor of exercise behavior during this period was fear of weight gain. Recent studies have highlighted the potential etiological centrality of fear of weight gain in eating disorder development, and results from the current paper underscore this cogntive feature as particularly salient in the prediction of maldaptive exercise [@levinsonEatingDisorderFear2020]. The strong associations between fear of weight gain and both exercise for weight loss and maldaptive exercise suggest that youth who are afraid of gaining weight may experiment with exercise as a means of managing or mitigating this fear, which, in some cases, could entrench exercise in a maladaptive, fear-based behavioral pattern. Interventions which address eating disorder cognitions to prevent eating disorder behaviors should consider fear of weight gain as a potential target to preempt risk for the development of maladaptive exercise patterns. 

In addition to fear of weight gain, thin-ideal internalization at age 14 years was associated with increases in odds of maladaptive exercise for both boys and girls, along with exercise for weight loss amogst girls, all with modest effects (odds increasing ~10% for a one standard deviation increase in mean thin-ideal internalization score).  Body dissatisfaction, on the other hand, was not a consistent predictor of maladaptive exercise patterns. 

With regards to interactions with age, as expected, cognitive predictors were generally strongest at points more proximal to when those predictors were measured (age 14), with small reductions in predictive power at later ages.

### Age 13 BMI

While there were no a priori hypotheses regarding BMI as a predictor of maladaptive exercise, BMI Z-score at age 13 was consistently, positively associated with both odds of exercise for weight loss and maladaptive exercise in the cohort. Further, BMI z-score at age 13 related to increased odds of transitioning from the 'no exericse for weight loss' group to the 'exercise for weight loss' group over time. On the one hand, it is possible that youth at higher BMIs are both receiving and internalizing messages from media, peers, and health professionals to utilize exercise for weight loss at higher rates. However, the association between BMI at age 13 with not only exercise for weight loss but also maladaptive exercise suggests that the employment of exercise for weight management is not leading to exercise behavior that is exclusively innocuous or health promoting, and that youth living in larger bodies may be particuarly susceptible to the development of a psychologically problematic relationship with exercise. 

## Limitations 

### Data harmonization across age

As mentioned previously, a first limitation of analyses were slightly different response options at varying ages. Data harmonization in the current study was informed by the existing literature on maladaptive exercise; however, complete harmonization across age was not possible, and may influence endorsement of exercise for weight loss and maladaptive exercise symptoms across age. 

### Assessment gap between 18-24 years

Second, while individuals provided data every two years from ages 14-18, there was a longer gap between measurements from ages 18 to 24 years. The time period between assessments was modeled reflecting real time in both analytic approaches; however, this larger gap leaves some question as to the nature of change in exercise patterns during transition to young adulthood.

### Model Convergence for Transition Models

Third, while maladaptive exercise was common in both boys and girls as individuals transitioned to young adulthood, it was less common (< 7% endorsement) amongst boys at younger ages. Due to lower levels of endorsement at younger ages along with relatively few assessment points present per individual, there was limited ability to examine predictors of transitions between exercise groups amongst boys. 

### Snapshot of Anglo-Western Culture

Fourth, while relatively rich information about exercise cognitions across development in this cohort provides a snapshot of the prevalence of maladaptive exercise behaviors, this snapshot is necessarily contextualized in time and place, specifically, a predominately White sample of youth in the early 21st century. It is likely that rates of exercise for weight loss and maladaptive exercise vary in other adolescent populations. 

## Future Directions

The current paper lays groundwork to untangle distinctions between adaptive and maladaptive exerise behavior across adolescence. First, while initial work suggests that maladaptive exercise predicts exacerbation of other eating disorder behaviors [@schaumbergProspectiveAssociationsDriven2022; @brosofExploringContributionExercise2020], we know less about associations between exercise for weight loss and eating disorder risk, particularly in later adolescence. Second, the degree to which psychological motivations for exercise and maladaptive exercise symptoms associate with objective exercise behavior (frequency, intensity of exercise) and the degree to which frequency and intensity of exercise interact with weight loss motivations in the development and maintenance of maldatpive exercise patterns is currently unclear. Finally, examination of prospective associations between exercise for weight loss, BMI, and eating disorder symptoms would clarify the degree to which exercise for weight loss impacts BMI trajectories in either adaptive or maladaptive ways, including whether exercise for weight loss is likely to pre-date growth curve deviations that signal disordered eating. 

## Conclusions

Building off of initial work examining endorsement of exercise for weight loss and maladaptive exercise in early adolescence, the current study examines rates of exercise for weight loss and maladaptive exercise longitudinally across ten years of adolescent and young adult development. Findings highlight the high and increasing rates of both exercise for weight loss and maladaptive exercise across adolescence, and bring to question the degree to which marketing and public health messages associating exercise with weight loss may impact young people's experiences of exercise. Further, those who are cognitively at risk for eating disorder development in early adolescnce may be most likely to internalize weight loss  motivations for exercise and develop a problematic relationship with exercise. Given current findings, efforts to unpair exercise from weight loss motivations amongst teens and young adults, particularly those otherwise at risk for disordered eating, may be indicated. Further, interventions which promote greater attunement to exercise reinforces other than weight management (e.g. social connection, mastery of new skills, emotion regulation) could aid in supplanting weight loss motivations to develop more sustainable, adaptive, and flexible exercise habits amongst youth. 

