### Cognitive Eating Disorder Features

| Construct                   | Age        | Measure                                                                                                                                                                                   | Diagnostic Criteria Cutoffs                                                            |
|:---------------|:---------------|:------------------------|:---------------|
| Thin ideal internalization  | 14         | IBSS-R appearance ideals rated on a 5-point Likert scale from 'strongly agree' to 'strongly disagree.'                                                                                    |                                                                                        |
| Pressure to Lose Weight     | 14         | Perceived Sociocultural Pressure Scale.                                                                                                                                                   |                                                                                        |
| Pressure to Increase Muscle | 14         | Perceived Sociocultural Pressure Scale. .                                                                                                                                                 |                                                                                        |
| External Eating             | 14         | Dutch Eating Behavior Questionnaire (DEBQ)                                                                                                                                                |                                                                                        |
| Restrained Eating           | 14         | Dutch Eating Behavior Questionnaire (DEBQ)                                                                                                                                                |                                                                                        |
| Emotional Eating            | 14         | Dutch Eating Behavior Questionnaire (DEBQ)                                                                                                                                                |                                                                                        |
| Weight/Shape Concern        | 14         | Assessed using 2-items from the McKnight risk survey asking how how happy participants are with thier bodies and if weight has made a difference in how they have felt about their bodies | **'Very unhappy' or weight making 'A lot/quite a lot' of difference in how one feels** |
| Body Dissatisfaction        | 14, 18, 24 | Satisfaction with body parts on a 5-point Likert scale, from 'extremely satisfied' to 'extremely dissatisfied' with higher values indicating higher dissatisfaction.                      | **Average score of 'moderately dissatisfied' or higher**                               |
| Dieting                     | 14, 16, 18 | Frequency during the past year young person went on a diet to lose weight/keep from gaining weight.                                                                                       | **Dieting reported in the past year 'several times' or more**                          |
| Fear of Weight Gain         | 14, 24     | Participants reported the degree they worried about gaining a little weight (two pounds) in the past year.                                                                                | **Fear of weight gain endorsed 'a lot' or 'all the time'**                             |
| Weight intentions           | 14, 18     | Participants reported what they are trying to do with their weight.                                                                                                                       | **Weight loss intentions reported**                                                    |
| Weight Perception           | 14, 18     | Participants reported their perception of their weight.                                                                                                                                   |                                                                                        |
| Weight Valuation            | 18         | Participants reported the degree to which their weight has made a difference to how they feel about themselves.                                                                           | **Weight valuation reported 'somewhat' or more**                                       |
| Feeling Fat                 | 24         | Participant reported the frequency that they have felt fat in the past year.                                                                                                              | **Feeling fat reported xxx or more**                                                   |
